hivex: Use OCaml bytecode compiler for caml_raise_with_args check
On installations where no native OCaml compiler is available, the
test program can't be compiled and so we get this message:

,----
| checking for function caml_raise_with_args... not found
`----

This breaks building of the OCaml bindings.

,----
| gcc -std=gnu99 -I.. -I/usr/lib/ocaml -I../ocaml -I../lib   -g -O2 -fPIC -Wall -c hivex_c.c
| hivex_c.c:52: error: static declaration of 'caml_raise_with_args' follows non-static declaration
| /usr/lib/ocaml/caml/fail.h:30: note: previous declaration of 'caml_raise_with_args' was here
| make[2]: *** [hivex_c.o] Error 1
`----

(Successfully tested on Debian/unstable on alpha)