sh: Fix signed/unsigned issues in setval command.
Use size_t instead of int for counting sizes of strings etc.

Also remove this warning:

hivexsh.c: In function 'main':
hivexsh.c:923:7: error: missed loop optimization, the loop counter may overflow [-Werror=unsafe-loop-optimizations]
       for (j = 0; j <= /* sic */ nr_chars; ++j) {
       ^~~
hivexsh.c:942:7: error: missed loop optimization, the loop counter may overflow [-Werror=unsafe-loop-optimizations]
       for (j = 0; j <= /* sic */ nr_chars; ++j) {
       ^~~